export enum EffectType {
    AOE = 'AOE',
    STUN = 'STUN',
    REFLECT = 'REFLECT',
    ENERGY_REMOVAL = 'ENERGY_REMOVAL',
    ENERGY_DRAIN = 'ENERGY_DRAIN',
    DOT = 'DOT',
    PREPARATION = 'PREPARATION',
    INVULNERABLE = 'INVULNERABLE',
    HEAL = 'HEAL',
    DAMAGE_REDUCTION = 'DAMAGE_REDUCTION',
    DESTRUCTABLE_DEFENSE = 'DESTRUCTABLE_DEFENSE',
    INCREASE_DAMAGE = 'INCREASE_DAMAGE',
    NONE = 'NONE'

}
